<?php

return [
    // Appartamento 1
    [
        "apartment_id"=>1,
        "service_id"=>1
    ],
    [
        "apartment_id"=>1,
        "service_id"=>2
    ],
    [
        "apartment_id"=>1,
<<<<<<< HEAD
=======
        "service_id"=>4
    ],
    [
        "apartment_id"=>1,
>>>>>>> main
        "service_id"=>6
    ],
    [
        "apartment_id"=>1,
<<<<<<< HEAD
        "service_id"=>5
    ],
    [
=======
        "service_id"=>7
    ],
    [
        "apartment_id"=>1,
        "service_id"=>9
    ],
    [
        "apartment_id"=>1,
        "service_id"=>10
    ],

    // Appartamento 2
    [
>>>>>>> main
        "apartment_id"=>2,
        "service_id"=>3
    ],
    [
        "apartment_id"=>2,
        "service_id"=>4
    ],
    [
        "apartment_id"=>2,
        "service_id"=>5
    ],
    [
        "apartment_id"=>2,
<<<<<<< HEAD
        "service_id"=>1
=======
        "service_id"=>7
>>>>>>> main
    ],
    [
        "apartment_id"=>2,
        "service_id"=>11
    ],
<<<<<<< HEAD
    [
        "apartment_id"=>2,
        "service_id"=>6
=======

    // Appartamento 3
    [
        "apartment_id"=>3,
        "service_id"=>1
    ],
    [
        "apartment_id"=>3,
        "service_id"=>4
>>>>>>> main
    ],
    [
        "apartment_id"=>3,
        "service_id"=>6
    ],
    [
        "apartment_id"=>3,
<<<<<<< HEAD
        "service_id"=>1
    ],
    [
        "apartment_id"=>3,
        "service_id"=>9
    ],
    [
        "apartment_id"=>3,
        "service_id"=>10
    ],
    [
        "apartment_id"=>3,
        "service_id"=>3
    ],
    [
        "apartment_id"=>4,
=======
>>>>>>> main
        "service_id"=>7
    ],
    [
        "apartment_id"=>3,
        "service_id"=>9
    ],
    [
<<<<<<< HEAD
        "apartment_id"=>5,
        "service_id"=>10
    ],
    [
        "apartment_id"=>5,
        "service_id"=>8
    ],
    [
        "apartment_id"=>6,
        "service_id"=>4
    ],
    [
        "apartment_id"=>6,
        "service_id"=>2
    ],
    [
        "apartment_id"=>6,
        "service_id"=>3
=======
        "apartment_id"=>3,
        "service_id"=>11
>>>>>>> main
    ],

    // Appartamento 4
    [
<<<<<<< HEAD
        "apartment_id"=>6,
        "service_id"=>4
    ],
    [
        "apartment_id"=>6,
        "service_id"=>6
    ],
    [
        "apartment_id"=>7,
        "service_id"=>2
    ],
    [
        "apartment_id"=>7,
        "service_id"=>4
    ],
    [
        "apartment_id"=>7,
        "service_id"=>8
    ],
    [
        "apartment_id"=>7,
        "service_id"=>10
    ],
    [
        "apartment_id"=>8,
        "service_id"=>9
    ],
    [
        "apartment_id"=>8,
        "service_id"=>7
    ],
    [
        "apartment_id"=>8,
        "service_id"=>5
    ],
    [
        "apartment_id"=>8,
        "service_id"=>11
    ],
    [
        "apartment_id"=>8,
        "service_id"=>10
    ],
    [
        "apartment_id"=>8,
        "service_id"=>1
    ],
    [
        "apartment_id"=>8,
        "service_id"=>2
    ],
    [
        "apartment_id"=>8,
        "service_id"=>3
    ],
    [
        "apartment_id"=>9,
        "service_id"=>4
    ],
    [
        "apartment_id"=>9,
        "service_id"=>11
    ],    
    [
        "apartment_id"=>9,
        "service_id"=>2
    ],
    [
        "apartment_id"=>9,
        "service_id"=>8
    ],
    [
        "apartment_id"=>10,
=======
        "apartment_id"=>4,
>>>>>>> main
        "service_id"=>2
    ],
    [
        "apartment_id"=>4,
        "service_id"=>4
    ],
    [
<<<<<<< HEAD
        "apartment_id"=>10,
        "service_id"=>6
    ],
    [
        "apartment_id"=>10,
        "service_id"=>8
    ],
    [
        "apartment_id"=>11,
        "service_id"=>1
    ],
    [
        "apartment_id"=>11,
        "service_id"=>3
    ],
    [
        "apartment_id"=>11,
        "service_id"=>5
    ],
    [
        "apartment_id"=>11,
        "service_id"=>7
    ],    
    [
        "apartment_id"=>11,
        "service_id"=>9
    ],
    [
        "apartment_id"=>11,
        "service_id"=>11
    ],    
    [
        "apartment_id"=>11,
        "service_id"=>4
    ],
    [
        "apartment_id"=>11,
        "service_id"=>6
    ],
    [
        "apartment_id"=>12,
=======
        "apartment_id"=>4,
>>>>>>> main
        "service_id"=>5
    ],
    [
        "apartment_id"=>4,
        "service_id"=>7
    ],
    [
        "apartment_id"=>4,
        "service_id"=>8
    ],
    [
<<<<<<< HEAD
        "apartment_id"=>12,
        "service_id"=>1
    ],
    [
        "apartment_id"=>12,
        "service_id"=>2
    ],
    [
        "apartment_id"=>13,
        "service_id"=>4
    ],
    [
        "apartment_id"=>13,
        "service_id"=>6
    ],
    [
        "apartment_id"=>13,
        "service_id"=>1
    ],    
    [
        "apartment_id"=>13,
        "service_id"=>9
    ],
    [
        "apartment_id"=>14,
        "service_id"=>11
    ],
    [
        "apartment_id"=>14,
        "service_id"=>2
    ],
    [
        "apartment_id"=>14,
=======
        "apartment_id"=>4,
>>>>>>> main
        "service_id"=>9
    ],

    // Appartamento 5
    [
        "apartment_id"=>5,
        "service_id"=>3
    ],
    [
        "apartment_id"=>5,
        "service_id"=>6
    ],
    [
        "apartment_id"=>5,
        "service_id"=>7
    ],
    [
        "apartment_id"=>5,
        "service_id"=>8
    ],
    [
        "apartment_id"=>5,
        "service_id"=>10
    ],
    [
        "apartment_id"=>5,
        "service_id"=>11
    ],

    // Appartamento 6
    [
        "apartment_id"=>6,
        "service_id"=>1
    ],
    [
        "apartment_id"=>6,
        "service_id"=>2
    ],
    [
        "apartment_id"=>6,
        "service_id"=>3
    ],
    [
<<<<<<< HEAD
        "apartment_id"=>15,
        "service_id"=>1
=======
        "apartment_id"=>6,
        "service_id"=>4
    ],
    [
        "apartment_id"=>6,
        "service_id"=>5
    ],
    [
        "apartment_id"=>6,
        "service_id"=>6
    ],
    [
        "apartment_id"=>6,
        "service_id"=>7
    ],
    [
        "apartment_id"=>6,
        "service_id"=>8
    ],
    [
        "apartment_id"=>6,
        "service_id"=>9
    ],
    [
        "apartment_id"=>6,
        "service_id"=>10
    ],
    [
        "apartment_id"=>6,
        "service_id"=>11
    ],

    // Appartamento 7
    [
        "apartment_id"=>7,
        "service_id"=>2
    ],
    [
        "apartment_id"=>7,
        "service_id"=>3
    ],
    [
        "apartment_id"=>7,
        "service_id"=>4
    ],
    [
        "apartment_id"=>7,
        "service_id"=>7
>>>>>>> main
    ],
    [
        "apartment_id"=>15,
        "service_id"=>2
    ],    [
        "apartment_id"=>15,
        "service_id"=>4
    ],
    [
<<<<<<< HEAD
        "apartment_id"=>15,
        "service_id"=>11
    ],
    [
        "apartment_id"=>16,
        "service_id"=>9
    ],
    [
        "apartment_id"=>16,
        "service_id"=>1
    ],
    [
        "apartment_id"=>16,
        "service_id"=>2
    ],
    [
        "apartment_id"=>17,
        "service_id"=>3
    ],
    [
        "apartment_id"=>17,
        "service_id"=>2
    ],
    [
        "apartment_id"=>18,
        "service_id"=>5
    ],
    [
        "apartment_id"=>18,
        "service_id"=>7
    ],
    [
        "apartment_id"=>18,
        "service_id"=>8
    ],
    [
        "apartment_id"=>19,
        "service_id"=>10
    ],
    [
        "apartment_id"=>19,
        "service_id"=>7
    ],
    [
        "apartment_id"=>19,
        "service_id"=>3
    ],
    [
        "apartment_id"=>19,
        "service_id"=>5
    ],
    [
        "apartment_id"=>19,
        "service_id"=>2
    ],
    [
        "apartment_id"=>20,
        "service_id"=>8
    ],
    [
        "apartment_id"=>20,
        "service_id"=>5
    ],
    [
        "apartment_id"=>20,
        "service_id"=>7
    ],
    [
        "apartment_id"=>20,
        "service_id"=>1
    ],    [
        "apartment_id"=>20,
        "service_id"=>11
    ],
    [
        "apartment_id"=>20,
        "service_id"=>3
    ],
    [
        "apartment_id"=>20,
        "service_id"=>4
    ],



=======
        "apartment_id"=>7,
        "service_id"=>10
    ],

    // Appartamento 8
    [
        "apartment_id"=>8,
        "service_id"=>1
    ],
    [
        "apartment_id"=>8,
        "service_id"=>2
    ],
    [
        "apartment_id"=>8,
        "service_id"=>5
    ],
    [
        "apartment_id"=>8,
        "service_id"=>7
    ],
    [
        "apartment_id"=>8,
        "service_id"=>8
    ],
    [
        "apartment_id"=>8,
        "service_id"=>9
    ],
    [
        "apartment_id"=>8,
        "service_id"=>11
    ],

    // Appartamento 9
    [
        "apartment_id"=>9,
        "service_id"=>1
    ],
    [
        "apartment_id"=>9,
        "service_id"=>3
    ],
    [
        "apartment_id"=>9,
        "service_id"=>7
    ],
    [
        "apartment_id"=>9,
        "service_id"=>8
    ],

    // Appartamento 10
    [
        "apartment_id"=>10,
        "service_id"=>2
    ],
    [
        "apartment_id"=>10,
        "service_id"=>3
    ],
    [
        "apartment_id"=>10,
        "service_id"=>4
    ],
    [
        "apartment_id"=>10,
        "service_id"=>6
    ],
    [
        "apartment_id"=>10,
        "service_id"=>8
    ],
    [
        "apartment_id"=>10,
        "service_id"=>10
    ],
    [
        "apartment_id"=>10,
        "service_id"=>11
    ],

    // Appartamento 11
    [
        "apartment_id"=>11,
        "service_id"=>1
    ],
    [
        "apartment_id"=>11,
        "service_id"=>3
    ],
    [
        "apartment_id"=>11,
        "service_id"=>4
    ],
    [
        "apartment_id"=>11,
        "service_id"=>5
    ],
    [
        "apartment_id"=>11,
        "service_id"=>6
    ],
    [
        "apartment_id"=>11,
        "service_id"=>7
    ],

    // Appartamento 12
    [
        "apartment_id"=>12,
        "service_id"=>1
    ],
    [
        "apartment_id"=>12,
        "service_id"=>4
    ],
    [
        "apartment_id"=>12,
        "service_id"=>5
    ],
    [
        "apartment_id"=>12,
        "service_id"=>6
    ],
    [
        "apartment_id"=>12,
        "service_id"=>8
    ],
    [
        "apartment_id"=>12,
        "service_id"=>9
    ],
    
    // Appartamento 13
    [
        "apartment_id"=>13,
        "service_id"=>1
    ],
    [
        "apartment_id"=>13,
        "service_id"=>2
    ],
    [
        "apartment_id"=>13,
        "service_id"=>3
    ],
    [
        "apartment_id"=>13,
        "service_id"=>4
    ],

    [
        "apartment_id"=>13,
        "service_id"=>7
    ],
    [
        "apartment_id"=>13,
        "service_id"=>8
    ],
    [
        "apartment_id"=>13,
        "service_id"=>9
    ],

    // Appartamento 14
    [
        "apartment_id"=>14,
        "service_id"=>1
    ],
    [
        "apartment_id"=>14,
        "service_id"=>2
    ],
    [
        "apartment_id"=>14,
        "service_id"=>6
    ],
    [
        "apartment_id"=>14,
        "service_id"=>8
    ],
    [
        "apartment_id"=>14,
        "service_id"=>9
    ],
    [
        "apartment_id"=>14,
        "service_id"=>11
    ],

    // Appartamento 15
    [
        "apartment_id"=>15,
        "service_id"=>2
    ],
    [
        "apartment_id"=>15,
        "service_id"=>3
    ],
    [
        "apartment_id"=>15,
        "service_id"=>4
    ],
    [
        "apartment_id"=>15,
        "service_id"=>7
    ],
    [
        "apartment_id"=>15,
        "service_id"=>9
    ],
    [
        "apartment_id"=>15,
        "service_id"=>10
    ],
>>>>>>> main
];