<?php

return [
    [ //https://www.airbnb.it/rooms/2282623?federated_search_id=3d6c7e76-bc45-4c7c-932c-2bf0261b55c8&source_impression_id=p3_1649681563_F49abhs9EtqZ%2BlgB
    "name"=>"Zona Sant'Orsola,parcheggio gratuito, self check-in",
    "description"=>"Se ti serve un delizioso appartamento a pochi passi dall'ospedale S.Orsola,'La Casina' è quello che cerchi! Siamo in zona S.Vitale e Università. No zona ZTL. Se invece sei a Bologna in occasione delle fiere,pochi minuti di auto o taxi e sarai arrivato.",
    "rooms"=>3,
    "beds"=>2,
    "bathrooms"=>1,
    "square_meters"=>80,
    "address"=>"Via Giuseppe Massarenti 32, Bologna BO",
    "visible"=> true,
    "lat"=> 44.49347548,
    "lon"=> 11.37368134,
    ],
    [ //https://www.airbnb.it/rooms/13789381?federated_search_id=3a60ee4a-ccab-408b-b0bc-29fb93c0c920&source_impression_id=p3_1649681669_wyA0iAJQluIHZNQu
    "name"=>"Casa di Via Cappello numero 5",
    "description"=>"Centralissimo a pochi passi da tutto, Unica camera da letto dove si trova un letto matrimoniale e un divano letto consigliato per quattro persone, all' interno della camera ci sono le due finestre che affacciano su via Cappello angolo via Mazzini e Piazza delle Erbe, corridoio con armadio dove si possono trovare asciugamani pulite e lenzuola pulite, cucina abitabile con tutto ciò che occorre più un balcone interno dal quale è visibile la Torre dei Lamberti, più un piccolo bagno con il necessario",
    "rooms"=> 3,
    "beds"=> 4,
    "bathrooms"=> 1,
    "square_meters"=> 50,
    "address"=>"via Cappello n.5",
    "visible"=> true,
    "lat"=> 45.44250777,
    "lon"=> 10.99807370,
    ],
    [ //https://www.airbnb.it/rooms/597476197966578255?federated_search_id=65e3efbf-64d0-4acf-b706-5cdec9ea2e5f&source_impression_id=p3_1649681727_YPOpNeCXdfmlW6tW
    "name"=>"Green Room - Comfort in downtown with private bath",
    "description"=>"Room with windows and a private bathroom with shower.
    The room is equipped with a boiler for water and tea, coffee machine, and everything you need for a comfortable breakfast in your room at any time you wish.
    The room is equipped with
    Air conditioning system
    TV",
    "rooms"=>3,
    "beds"=>2,
    "bathrooms"=>2,
    "square_meters"=>100,
    "address"=>"via San Gregorio Armeno 15, Napoli NA, Campania, Italy",
    "visible"=> true,
    "lat"=>45.79662464,
    "lon"=>8.89459826,
    ],
    [ //https://www.airbnb.it/rooms/32285772?check_in=2022-04-30&check_out=2022-05-19&federated_search_id=2aab2c5e-eb39-4805-8310-1dfaadb42261&source_impression_id=p3_1649681810_iDENinY2TKI%2FJzOl
    "name"=>"Loft con giardino in zona Appia Antica 1",
    "description"=>"Il nostro loft è situato all'interno di una villa immersa nel verde, a ridosso del parco dell'Appia Antica, ed è l'ideale per un soggiorno nella Capitale all'insegna del relax e della tranquillità. L'appartamento dispone di un ingresso indipendente con affaccio sul giardino interno e si compone di soggiorno, cucina, bagno e un letto matrimoniale. I padroni di casa saranno a vostra disposizione per accogliervi e rendere il vostro soggiorno il più confortevole possibile.",
    "rooms"=> 3,
    "beds"=> 2,
    "bathrooms"=> 1,
    "square_meters"=> 60,
    "address"=>"Via Luigi Tosti, 00179 Roma RM",
    "visible"=> true,
    "lat"=> 41.87456520,
    "lon"=>12.51881277,
    ],
    [ //https://www.airbnb.it/rooms/51448589?federated_search_id=491d9402-6c3a-4994-8f92-ca68e8ba171a&source_impression_id=p3_1649681969_ETnRVakaPc0%2Bj%2BEV
    "name"=>"Cozy apartment with terrace in Milan",
    "description"=>"Cozy apartment with a beautiful terrace in a central location and in a quiet setting, just a few meters from the M5 GERUSALEMME (purple line) underground station. The neighborhood is very nice and well stocked with all kinds of shops and supermarkets, in particular very good restaurants. In the immediate surroundings of the Sempione park and the Chinatown neighbor.",
    "rooms"=>2,
    "beds"=>1,
    "bathrooms"=>1,
    "square_meters"=>64,
    "address"=>"Via Francesco Londonio 8, Milano MI",
    "visible"=>true,
    "lat"=>45.48002415,
    "lon"=> 9.16951778,
    ],
    [ //https://www.airbnb.it/rooms/40364407?federated_search_id=27a0c1a3-b11d-461f-8cb1-165ff65fa38f&source_impression_id=p3_1649682074_pn9jNBl0qylBzTvs
    "name"=>"LINIZIO APPARTAMENT",
    "description"=>"L’ alloggio è ubicato a 5 minuti dalla stazione di Porta Nuova , a 10 minuti da Piazza Vittorio, ad 1 minuto dal parco del Valentino.
    Dotato di Tv, Wi-Fi,cucina attrezzata, ampio bagno con doccia e lavatrice , di un comodo divano letto.
    Molto ben servito dai mezzi di trasporto, ed ottima vicinanza ai locali, negozi, punti di ristoro, del centro città.",
    "rooms"=>3,
    "beds"=>1,
    "bathrooms"=>1,
    "square_meters"=>35,
    "address"=>"Via Fratelli Calandra 4, Torino TO",
    "visible"=>true,
    "lat"=>45.06083452, 
    "lon"=>7.68900250,
    ],
    [ //https://www.airbnb.it/rooms/24446953?federated_search_id=cd0513f5-8d9b-4e3e-bde0-93dceebafdf3&source_impression_id=p3_1649682153_k0tffYRgaGGwSIqu
    "name"=>"Suite Casa Nova for 6 persons.",
    "description"=>"Apt. di 3 locali 85 m2 al 2. piano. Completamente restaurato nel 2018, arredamento lussuoso e elegante: ingresso. Soggiorno/sala da pranzo grande con 1 divano letto doppio e camino (solo con funzione decorativa), tavolo da pranzo e TV (schermo piatto). 1 camera matrimoniale. Angolo notte con 1 x 2 letti a castello. Grande cucina aperta (forno, lavastoviglie, 4 piastre cottura in vetroceramica, tostapane, forno a microonde, macchina da caffè elettrica, capsule per la macchina da caffè (Nestlè Dolce Gusto)) con bancone. Bagno/bidè/WC, doccia/WC, doccia idromassaggio, vasca idromassaggio. Riscaldamento, climatizzazione. Vista sulla località e Campo Santi Filippo e Giacomo. A disposizione: ferro da stiro, asciugacapelli. Prego notare: appartamento per non fumatori. No ascensore. Non ci sono costi aggiuntivi obbligatori da pagare in loco ad eccezione della tassa di soggiorno.",
    "rooms"=>3,
    "beds"=>3,
    "bathrooms"=>2,
    "square_meters"=>85,
    "address"=>"Calle Rimpeto la Sacrestia 15, Venezia VE",
    "visible"=>true,
    "lat"=>45.43569289,
    "lon"=>12.34216204,
    ],
    [ //https://www.airbnb.it/rooms/32285772?check_in=2022-04-30&check_out=2022-05-19&federated_search_id=2aab2c5e-eb39-4805-8310-1dfaadb42261&source_impression_id=p3_1649681810_iDENinY2TKI%2FJzOl
    "name"=>"Loft con giardino in zona Appia Antica",
    "description"=>"Il nostro loft è situato all'interno di una villa immersa nel verde, a ridosso del parco dell'Appia Antica, ed è l'ideale per un soggiorno nella Capitale all'insegna del relax e della tranquillità. L'appartamento dispone di un ingresso indipendente con affaccio sul giardino interno e si compone di soggiorno, cucina, bagno e un letto matrimoniale. I padroni di casa saranno a vostra disposizione per accogliervi e rendere il vostro soggiorno il più confortevole possibile.",
    "rooms"=>3,
    "beds"=>2,
    "bathrooms"=>1,
    "square_meters"=>40,
    "address"=>"Via Appia Antica 15, Roma RO",
    "visible"=>true,
    "lat"=>41.81255703, 
    "lon"=>12.56465406
    ],
    [ //https://www.airbnb.it/rooms/597476197966578255?federated_search_id=65e3efbf-64d0-4acf-b706-5cdec9ea2e5f&source_impression_id=p3_1649681727_YPOpNeCXdfmlW6tW
    "name"=>"NUOVO E STUPENDO LOFT",
    "description"=>"Meraviglioso e nuovo appartamento in mansarda arredato in maniera funzionale e dotato di tutto il necessario. Situato in una posizione perfetta a Riccione per chi vuole stare vicinissimo al mare. Potrete scendere e raggiungere a piedi per raggiungere la spiaggia in un minuto. L’appartamento, dotato anche di aria condizionata gratuita, può ospitare fino a 4 persone. In 4 minuti di macchina sarete nel famoso e rinomato Viale Ceccarini, proprio nel centro di Riccione. Non fartelo sfuggire!",
    "rooms"=> 6,
    "beds"=> 4,
    "bathrooms"=> 1,
    "square_meters"=> 60,
    "address"=>"
    Viale G. Leopardi, 22 Riccione RN ",
    "visible"=> true,
    "lat"=> 44.01138391,
    "lon"=> 12.64513415
    ],
    [ //https://www.airbnb.it/rooms/53194081?federated_search_id=ca29ac0e-bea2-4224-9110-79ef0707085e&source_impression_id=p3_1649682586_xM%2FMzWXw4LeYLEJN
    "name"=>"Relais Piazza Signoria",
    "description"=>"L'appartamento da noi proposto si trova a ridosso di Piazza della Signoria, Piazza dove ha sede Palazzo Vecchio, cuore politico della città da quando Cosimo I de’ Medici vi spostò la sua sede ufficiale nella metà del 500. La straordinaria abbondanza di capolavori che si possono ammirare in questa Piazza rende talmente facile compiere un viaggio nelle epoche e nella bellezza che quasi nessuno è disposto a rinunciarci. Condominio. Nel centro di Firenze, nel quartiere Piazza della Signoria, posizione tranquilla, nel cuore della città, in una zona pedonale. Nella casa: ascensore. Negozio 20 m, supermercato 500 m, ristorante, bar 20 m, stazione ferroviaria 'Firenze Santa Maria Novella' 1.2 km. Attrazioni nelle vicinanze: Piazza della Signoria 50 m, Galleria degli Uffizi 270 m, Museo del Bargello 350 m, Museo dell'Opera del Duomo 650 m, Palazzo Pitti 800 m, Galleria dell'Accademia 1 km.",
    "rooms"=> 6,
    "beds"=> 2,
    "bathrooms"=> 1,
    "square_meters"=> 130,
    "address"=>"Via Vacchereccia, 3, 50122 Firenze FI",
    "visible"=> true,
    "lat"=> 43.76945793,
    "lon"=> 11.25493953,
    ],
    [ //https://www.airbnb.com/rooms/30506460?federated_search_id=04caa04d-3959-4519-bc09-7369d84d068f&source_impression_id=p3_1649757437_fU3uCSTSU1SXoQ9G
    "name"=>"Plantes guest Napoli centro",
    "description"=>"The apartment is located just 250 meters from the second entrance of Garibaldi station, 2 minutes from a typical local market in Naples and in the middle of a lively and characteristic neighborhood. Guests can enjoy a relaxing common area with sofa, armchairs, bookshelves, kettle, and reception with lots of tourist material to enjoy the heart of the city, and more.",
    "rooms"=>5,
    "beds"=>2,
    "bathrooms"=>1,
    "square_meters"=>110,
    "address"=>"Via renovella, Napoli NA, Campania, Italy",
    "visible"=>true,
    "lat"=>40.84790432,
    "lon"=>14.26278577
    ],
    [ //https://www.airbnb.it/rooms/18485112?federated_search_id=0a47a531-ba22-4e2e-8ab0-a83648baddf9&source_impression_id=p3_1649682698_K1uWevE3mdYH3qi%2B
    "name"=>"Lollotà Castello WiFi con soppalco (IUN P1849)",
    "description"=>"Appartamento con soppalco restaurato nel 2017, al secondo piano di un palazzo storico di proprietà della famiglia, di fronte alla Cattedrale di S.Maria e all'antico Palazzo di Città.
    Il palazzo si trova nel cuore del centro storico di Cagliari, il quartiere medievale di Castello. Affaccia sua una piccola piazza dove si trova un ottimo bar per le colazioni e per gli aperitivi. Nello stesso palazzo una bottega di prodotti locali biologici.
    Riceve il sole durante tutta la mattina.",
    "rooms"=>1,
    "beds"=>1,
    "bathrooms"=>1,
    "square_meters"=>40,
    "address"=>"Via Alberto Lamarmora 25, Cagliari CA",
    "visible"=>true,
    "lat"=>39.21916599,
    "lon"=> 9.11608876,
    ],
    [ //https://www.airbnb.it/rooms/18224948?federated_search_id=76d7b654-68a1-422b-a25c-48695333bd9f&source_impression_id=p3_1649682824_dFH3nHlCm5xyKkLw
    "name"=>"Dépendance Cascata delle Marmore",
    "description"=>"La struttura situata in un bellissimo paesino medievale e costruita sul fianco della collina, si affaccia sulla vallata e offre una vista unica sulla Valnerina e sulla Cascata delle Marmore in lontananza. L'abitazione, ricavata in un angolo intimo e riservato del giardino, è separata dalla struttura principale ed è dotata di divano letto matrimoniale, terrazzo e bagno privato.
    La piscina con vista, il giardino e il cucinino sono ad uso esclusivo degli ospiti",
    "rooms"=>2,
    "beds"=>1,
    "bathrooms"=>1,
    "square_meters"=>40,
    "address"=>"Via Madonna della Strada 55, Torreorsina, TN",
    "visible"=>true,
    "lat"=>42.57369317, 
    "lon"=>12.73309658,
    ],
    [ //https://www.airbnb.it/rooms/19588901?federated_search_id=e984fae1-5329-4a03-8146-4b6699762bce&source_impression_id=p3_1649682935_YFKHcCv8GICpbtWX
    "name"=>"Suite Felisia",
    "description"=>"La Suite Felisia è un autentica casa in trullo ideale per una coppia.
                    Questo Trullo è stato appena restaurato usando esclusivamente materiali naturali e di pregio.
                    La casa è dotata di camera da letto, bagno, sala giorno, cucina completa e giardino attrezzato totalmente privato.",
    "rooms"=> 3,
    "beds"=> 1,
    "bathrooms"=> 1,
    "square_meters"=> 100,
    "address"=>"Contrada Colarossa 12, 70011 Alberobello BA",
    "visible"=>true,
    "lat"=> 40.80300207,
    "lon"=> 17.24629567,
    ],
    [ //https://www.airbnb.it/rooms/22063061?federated_search_id=29ffdf84-fda6-41b6-a3b8-86e2abbf94d8&source_impression_id=p3_1649683041_cZZzlja8De%2BsZTmH
    "name"=>"Artedimarco 1",
    "description"=>"il miniappartamento è fornito di tutto , sia in fatto di biancheria che di attrezzatura da cucina e stoviglie , potete prepararvi colazioni e pasti. Metto a disposizione anche alcuni cibi e bevande essenzialmente per la colazione e olio sale caffè zucchero spezie per il resto vi organizzerete a vostro piacimento. In bagno ho disposto un doccino uso bidet molto comodo per motivi di spazio. Ovviamente sono benvenuti tutti , senza distinzioni.",
    "rooms"=>3,
    "beds"=>2,
    "bathrooms"=>1,
    "square_meters"=>30,
    "address"=>"Via Cesarini Sforza 5, Vallene, TN",
    "visible"=>true,
    "lat"=>46.10828127, 
    "lon"=>11.04562574,
    ],
    [ //https://www.airbnb.it/rooms/22545970?federated_search_id=62d8819c-6577-4ef6-9292-42c22b22d69f&source_impression_id=p3_1649683084_NIiJT05kD6JGZFuG
    "name"=>"La Montanina for 6 persons.",
    "description"=>"Nota: se le date desiderate sono disponibili, potete procedere direttamente con la prenotazione al miglior prezzo. Il prezzo finale è già scontato. Ulteriori informazioni riguardo l'annuncio sono disponibili nella descrizione della casa.
    Apt. di 4 locali 90 m2, al pianterreno. Luminoso, in parte restaurato nel 2022, arredamento funzionale e confortevole: soggiorno/sala da pranzo con stufa svedese, angolo pranzo e TV (schermo piatto), DVD. Uscita sul giardino. 1 camera con 1 letto e 1 letto ribaltabile",
    "rooms"=>7,
    "beds"=>5,
    "bathrooms"=>2,
    "square_meters"=>90,
    "address"=>"Via Rinaldo Menardi 7, Cortina d'Ampezzo, BL",
    "visible"=>true,
    "lat"=>46.53790245,
    "lon"=>12.14089386,
    ],
];