<?php

return [
    [
        "apartment_id"=>1,
        "service_id"=>1
    ],
    [
        "apartment_id"=>1,
        "service_id"=>2
    ],
    [
        "apartment_id"=>2,
        "service_id"=>3
    ],
    [
        "apartment_id"=>2,
        "service_id"=>4
    ],
    [
        "apartment_id"=>2,
        "service_id"=>5
    ],
    [
        "apartment_id"=>3,
        "service_id"=>6
    ],
    [
        "apartment_id"=>4,
        "service_id"=>7
    ],
    [
        "apartment_id"=>4,
        "service_id"=>8
    ],
    [
        "apartment_id"=>4,
        "service_id"=>9
    ],
    [
        "apartment_id"=>5,
        "service_id"=>10
    ],
    [
        "apartment_id"=>5,
        "service_id"=>8
    ],
    [
        "apartment_id"=>1,
        "service_id"=>7
    ],
    [
        "apartment_id"=>2,
        "service_id"=>10
    ],
    [
        "apartment_id"=>3,
        "service_id"=>11
    ],
    [
        "apartment_id"=>6,
        "service_id"=>4
    ],
    [
        "apartment_id"=>10,
        "service_id"=>2
    ],
    [
        "apartment_id"=>10,
        "service_id"=>3
    ],
    [
        "apartment_id"=>11,
        "service_id"=>1
    ],
    [
        "apartment_id"=>11,
        "service_id"=>3
    ],
    [
        "apartment_id"=>12,
        "service_id"=>5
    ],
    [
        "apartment_id"=>12,
        "service_id"=>8
    ],
    [
        "apartment_id"=>12,
        "service_id"=>1
    ],
    [
        "apartment_id"=>13,
        "service_id"=>4
    ],
    [
        "apartment_id"=>14,
        "service_id"=>11
    ],
    [
        "apartment_id"=>14,
        "service_id"=>2
    ],
    [
        "apartment_id"=>14,
        "service_id"=>9
    ],
    [
        "apartment_id"=>15,
        "service_id"=>10
    ],
    [
        "apartment_id"=>15,
        "service_id"=>3
    ],
    [
        "apartment_id"=>6,
        "service_id"=>7
    ],
    [
        "apartment_id"=>7,
        "service_id"=>8
    ],
    [
        "apartment_id"=>8,
        "service_id"=>9
    ],
    [
        "apartment_id"=>8,
        "service_id"=>4
    ],
    [
        "apartment_id"=>9,
        "service_id"=>4
    ],
    [
        "apartment_id"=>9,
        "service_id"=>11
    ]
];