<?php

return [
    [
        "email"=>"a@a.it",
        "password"=>"provapro",
        "name"=>"Antony",
        "lastname"=>"Morgante",
        "birth_date"=>null,
        "phone"=>null
    ],
    [
        "email"=>"b@a.it",
        "password"=>"provapro",
        "name"=>"Stefano",
        "lastname"=>"Martignoni",
        "birth_date"=>null,
        "phone"=>null
    ],
    [
        "email"=>"c@a.it",
        "password"=>"provapro",
        "name"=>"Ghadeer",
        "lastname"=>"Shamshoum",
        "birth_date"=>null,
        "phone"=>null
    ],
    [
        "email"=>"d@a.it",
        "password"=>"provapro",
        "name"=>"Gianluca",
        "lastname"=>"Benedetti",
        "birth_date"=>null,
        "phone"=>null
    ],
    [
        "email"=>"e@a.it",
        "password"=>"provapro",
        "name"=>"Fabio",
        "lastname"=>"Losa",
        "birth_date"=>null,
        "phone"=>null
    ],
];